### ISSUE TITLE
ThingyConnection: Error 8 on LG K8

### ISSUE THREAD

**Issue by neokril** [NordicSemiconductor/Android-Nordic-Thingy#7]
SCENARIO 1:
1. Run Andriod-Nordic-Thingy application (master, 2dfe47c) on LG K8 (Android 6.0 build MRA58K SW version V10g-CIS-XX)
2. Connect to Thingy

EXPECTED:
It works

OBSERVED:
In 5% of cases it crashes.
```
11-23 13:31:47.373 8391-8391/no.nordicsemi.android.nrfthingy D/BluetoothGatt: discoverServices() - device: E8:2D:5B:3B:C8:0D
11-23 13:31:47.403 8391-8402/no.nordicsemi.android.nrfthingy D/BluetoothGatt: onSearchComplete() = Device=E8:2D:5B:3B:C8:0D Status=0
11-23 13:31:47.403 8391-8402/no.nordicsemi.android.nrfthingy V/ThingyConnection: Service discovery completed
11-23 13:31:47.403 8391-8402/no.nordicsemi.android.nrfthingy V/ThingyConnection: Reading thingy config chars
11-23 13:31:47.403 8391-8402/no.nordicsemi.android.nrfthingy V/ThingyConnection: Reading battery characteristic
11-23 13:31:47.403 8391-8402/no.nordicsemi.android.nrfthingy V/ThingyConnection: Reading environment config chars
11-23 13:31:47.403 8391-8402/no.nordicsemi.android.nrfthingy V/ThingyConnection: Reading motion config chars
11-23 13:31:51.887 8391-8402/no.nordicsemi.android.nrfthingy D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=5 device=E8:2D:5B:3B:C8:0D
11-23 13:31:51.888 8391-8402/no.nordicsemi.android.nrfthingy V/ThingyConnection: Error 8 : E8:2D:5B:3B:C8:0D
11-23 13:31:51.890 8391-8402/no.nordicsemi.android.nrfthingy D/BluetoothGatt: close()
11-23 13:31:51.890 8391-8402/no.nordicsemi.android.nrfthingy D/BluetoothGatt: unregisterApp() - mClientIf=5
11-23 13:31:51.908 8391-8391/no.nordicsemi.android.nrfthingy D/AndroidRuntime: Shutting down VM

 FATAL EXCEPTION: main
                                                                               Process: no.nordicsemi.android.nrfthingy, PID: 8391
                                                                               java.lang.IllegalArgumentException: Descriptor is not valid
                                                                                   at no.nordicsemi.android.thingylib.ThingyConnection$Request.start(ThingyConnection.java:3073)
                                                                                   at no.nordicsemi.android.thingylib.ThingyConnection.processNext(ThingyConnection.java:3020)
                                                                                   at no.nordicsemi.android.thingylib.ThingyConnection.access$1500(ThingyConnection.java:77)
                                                                                   at no.nordicsemi.android.thingylib.ThingyConnection$5.run(ThingyConnection.java:2938)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
```

In other cases it quickly disconnects after connecting with "ThingyConnection: Error 8" message in the log
```
11-23 13:24:43.754 2356-8372/? D/BtGatt.GattService: registerForNotification() - address=E8:2D:5B:3B:C8:0D enable: true
11-23 13:24:43.755 2356-2440/? D/BtGatt.GattService: onRegisterForNotifications() - address=null, status=0, registered=1, charUuid=ef680204-9b35-4933-9b10-52ffa9740042
11-23 13:24:43.757 2356-2440/? D/BtGatt.GattService: onDisconnected() - clientIf=5, connId=5, address=E8:2D:5B:3B:C8:0D
11-23 13:24:43.758 8391-8402/no.nordicsemi.android.nrfthingy D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=5 device=E8:2D:5B:3B:C8:0D
11-23 13:24:43.758 8391-8402/no.nordicsemi.android.nrfthingy V/ThingyConnection: Error 8 : E8:2D:5B:3B:C8:0D
```

SCENARIO 2:
1. Run simple application with thingylib from (master, 2dfe47c) on LG K8 (Android 6.0 build MRA58K SW version V10g-CIS-XX). The application only discovers Thingy with "no.nordicsemi.android.support.v18:scanner:1.0.0" and connects to it.

EXPECTED:
It works

OBSERVED: 
The same as in SCENARIO 1

**Comment by neokril** [comment]
Looks like increasing maximum connection interval helps. With the following line in `onServiceDiscoveryCompleted` it keeps connection without disconnect:

```
// Default max connection interval (without below line) is 24
mThingySdkManager.setMaximumConnectionIntervalUnits(device, 96);
```


But this workaround does not help with crashes. Also sometimes disconnect happens **before** service discovery is completed.

**Comment by roshanrajaratnam** [comment]
Hi, Thanks for reporting this issue, I will look in to this and get back to you.

**Comment by mikesmales** [comment]
Hello, 

Is there an update on this issue please? 

We are experiencing the same issue here also on a number of Android devices and have had no luck with the suggested workaround. It is really holding up our ability to prototype with the Thingy. 

Devices are: 
Google Pixel XL 
Samsung Galaxy S7 edge 
Nexus 7 

Any help would be greatly appreciated. Thanks.

**Comment by philips77** [comment]
Hi @mikesmiles,
@roshanrajaratnam wrote that he'll look into it and get back here. I'm sure he will, the issue is not even one year old ;)
Ok, but seriously, we'll about to release BLE Library v2. Hopefully it will fix some issues that you encounter. We'll try to migrate Nordic Thingy as well, but we are busy with other tasks right now. We'll do our best. Please, keep pinging us if you don't see any activity.

**Comment by mikesmales** [comment]
Hi @philips77 thank you for your response and @roshanrajaratnam there is no time like the present :)

Do please let me know if you have any other workarounds for the issue or if there are any Android devices that perhaps do not suffer from this. 

Looking forward to seeing BLE Library v2.

**Comment by roshanrajaratnam** [comment]
@mikesmales @philips77 talking about backlogs right, and some issues never disappear in to the past! ;)

@mikesmales The version on the playstore seem to work fine on the pixel xl I'm testing on right now. Unfortunately I don't have other devices to reproduce the issue. However, do you have any steps to reproduce this? What version of the Thingy FW are you using?

**Comment by mikesmales** [comment]
@roshanrajaratnam thanks for looking into this. 

We've observed that the Thingy disconnects after we access the microphone via `enableThingyMicrophone` in a matter of seconds, perhaps related to configuring the MTU. It does still disconnect if not accessing the microphone, just takes a little longer. 

We've seen the issue with Nordic Thingy app on Google Plav v1.3.4 and using firmware 2.1.0 as well as the code built from this repo. 

Steps to reproduce: 
1. connect to Thingy
2. go to the sound fragment and access the microphone

Observe - in roughly 10-20 seconds it will disconnect with the error: 
`00:27 V/ThingyConnection: Error 8 : F6:B9:18:04:0E:7C`

We suspected it might be BLE version but can reproduce with BLE 4.2.

**Comment by roshanrajaratnam** [comment]
Right ok. There was an issue with some devices relating to the MTU some time ago, but that was specifically on a Motorola Nexus 6 running Android 6.0 as far as I recall. Also what are the connection intervals used here? Have you changed anything there?

**Comment by mikesmales** [comment]
We've tried changing the maximum connection interval using the workaround above: 

`mThingySdkManager.setMaximumConnectionIntervalUnits(device, 96);`

But this didn't seem to have any affect. Is there anything else we should be trying?

**Comment by roshanrajaratnam** [comment]
@mikesmales could you try with the playstore version to see, if the minimum 6 and max 24 connection intervals please? I've tested agains the app defaults and seem to work fines. I changed the max connection interval to 96 units  just like on your device and that works fine too.

**Comment by one-giant-leap** [comment]
I would consider whether the disconnection is occurring because the Thingy is resetting due to an error code being returned in the following call to the sd_ble_gatts_exchange_mtu_reply() function: https://github.com/NordicSemiconductor/Nordic-Thingy52-FW/blob/master/source/modules/m_ble.c#L404

**Comment by philips77** [comment]
@jorgenmk

**Comment by roshanrajaratnam** [comment]
@one-giant-leap Have you made any changes to the firmware? It would be nice to debug this using nRF Connect for Android. What you could do is connect to the Thingy and do an MTU request, you can find the option on the overflow icon above the services list. If possible please share the logs with us. You can swipe to the right to see the logs. Let us know how it goes.

**Comment by philips77** [comment]
Hello, another half of a year passed. Any updates here?

**Comment by roshanrajaratnam** [comment]
I guess we can close it if there's no activity and reopen if required!
